server:
  port: 8081
spring:
  application:
    name: orders
  datasource:
    url: jdbc:mysql://database:3306/orders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/